debug: true
server:
    port: 3000
spring:
    datasource:
        password: ''
        url: jdbc:mysql://localhost:3306/stanbicdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                
twilio:
    account_sid: ACfed0860440da307791ffe180f3af35ed
    auth_token: 12d477e0f41e85aad8115e64a85d18f1
    trial_number: +15412503715

jwt:
    secret: stanbic_secret